global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using MonkeyFinder.Model;
global using MonkeyFinder.Services;
global using MonkeyFinder.View;
global using MonkeyFinder.ViewModel;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Net.Http.Json;
